manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: 246ra
      url-base: https://github.com/246ra
    - name: eswai
      url-base: https://github.com/eswai
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver
      remote: 246ra
      revision: ball_one_click
    - name: zmk-naginata
      remote: eswai
      revision: main
  self:
    path: config
